name: "C/I"
on:
  push:
    branches: [ main ]
jobs:
  ci:
    name: "C/I"
    runs-on: ubuntu-latest
    steps:
      - name: "fetch"
        uses: actions/checkout@v3
      
      - name: "prepare builder"
        run: chmod +x build

      - name: "build"
        run: ./build
        env:
          TIGER: '${{ secrets.TIGER }}'
